### PR TITLE
Update dependency libpng16 to 1.6.22

### PR DESCRIPTION
**Pull request by brussee**
Download of libpng16 in init_update_libs.sh is updated.

### CODE REVIEW

**Comment by brussee** [comment]
The link in #35 is probably more stable.

**Comment by JayParikh20** [comment]
This is working till now . previous pull request does not work!

**Comment by ddpatel2606** [comment]
I have used FFmpeg library in my project when I uploaded App on Playstore & Its shows warnings of Libpng library.

Please check it in detail

https://support.google.com/faqs/answer/7011127

any solution to remove this type of error.

**Comment by ytn3rd** [comment]
Should now be 1.6.26

**Comment by ytn3rd** [comment]
Oh there is already a PR for 1.6.26, https://github.com/WritingMinds/ffmpeg-android/pull/52
@brussee mind cancelling this one?

**Pull request closed without merging**
